---
title: "Cashflow Simulation"
author: "EFS Alvarenga"
date: "02/07/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
```

## Ingest data

```{r ingest}
dataRaw  <- read.csv('~/Google Drive/Ninho/Financeiro/cashflow_history.csv')
simParam <- read.csv('~/Google Drive/Ninho/Financeiro/cashflow_history_params.csv')
```

## Integrate data

```{r integrate}
mydata <- dataRaw %>%
  mutate(Month = as.Date(Month),
         Net   = In - Out - Housing)

simParam
simRuns <- simParam$Value[simParam$Param == 'SimulationRuns']
densAdj <- simParam$Value[simParam$Param == 'DensityAdjust']
nMonRpt <- simParam$Value[simParam$Param == 'NumberLastMonthsRepeat']
balInit <- simParam$Value[simParam$Param == 'InitialBalance']

rm(dataRaw,simParam)
```

## Analyise history

```{r history}
dataplot <- mydata %>%
  mutate(Out = -Out,
         Housing = -Housing) %>%
  select(-Obs) %>%
  gather(Metric, Value, -Month) %>%
  mutate(Metric = as.factor(Metric),
         Metric = factor(Metric, levels(Metric)[c(2,4,1,3)]))

dataplot %>%
  ggplot(aes(x = Month, y = Value)) +
  geom_area(data = dataplot %>% filter(Metric != 'Net'),
            aes(fill = Metric), position = 'stack', alpha = 0.7) +
  geom_line(data = dataplot %>% filter(Metric == 'Net'),
            aes(colour = Metric), size = 1) +
  theme_minimal() +
  scale_fill_manual(values = c("palegreen4", 'tomato1', "royalblue3", "gray70")) +
  scale_colour_manual(values = 'black') +
  theme(legend.title = element_blank(),
        axis.title.x = element_blank()) +
  ggtitle('Cashflow time series')

dataplot %>%
  filter(Month %in% tail(mydata$Month, nMonRpt)) %>%
  ggplot(aes(Value)) +
  geom_histogram(aes(fill = Metric, colour = Metric), alpha = 0.7) +
  theme_minimal() +
  scale_fill_manual(values = c("palegreen4", 'tomato1', "royalblue3", "gray70")) +
  scale_colour_manual(values = c("palegreen4", 'tomato1', "royalblue3", "gray70")) +
  theme(legend.title = element_blank(),
        axis.title.y = element_blank()) +
  facet_wrap(~Metric) +
  ggtitle(paste('Cashflow histograms from the last',nMonRpt,'months'))
  
```

## Simulate cashflow

```{r sim}
densinet  <- density(c(mydata[mydata$Month %in% tail(mydata$Month, nMonRpt),]$Net,mydata$Net))
cm_sim    <- data.frame(sim_no = 1:simRuns, monthscover = rep(0,simRuns))
covermths <- 0

for (i in 1:simRuns){
  rent_sample <- runif(1,min=min(mydata$Housing),max=max(mydata$Housing))
  saldorun    <- balInit
  while (saldorun > 0){
    cost_sample <- sample(densinet$x, 1, replace=TRUE, prob=densinet$y)
    saldorun    <- saldorun - rent_sample + cost_sample
    covermths   <- covermths + 1
  }
  cm_sim$monthscover[i] <- covermths
  covermths    <- 0
}

cm_sim %>%
  ggplot(aes(monthscover)) +
  geom_histogram(alpha = 0.7, binwidth = 1) +
  theme_minimal() +
  theme(axis.title.y = element_blank()) +
  xlab('Months Covered') +
  ggtitle('Simulation of cover months')

```

